export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";
